/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formdayny;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        list.add(new Khachhang("KH1", "Nguyễn Ngọc Sáng", 18, "Nam", "Bắc Giang", true));
        list.add(new Khachhang("KH3", "Mai Hoàng Phương Anh", 19, "Nữ", "Hà Nội", true));
        list.add(new Khachhang("KH5", "Nguyễn Văn Công", 18, "Nam", "Bắc Giang", false));
        list.add(new Khachhang("KH9", "Nguyễn Công Chiến", 18, "Nữ", "Hà Nội", true));
        addtable(list);
    }

    ArrayList<Khachhang> list = new ArrayList<>();

    public void addtable(ArrayList<Khachhang> list) {
        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        bang.setRowCount(0);
        for (Khachhang kh : list) {
            bang.addRow(new Object[]{kh.getMakh(), kh.getTenkh(), kh.getTuoi(), kh.getGioitinh(), kh.getDiachi(), kh.isTrangthai()});
        }
    }
    int index;

    public void display() {
        Khachhang kh = list.get(index);
        int vip = list.indexOf(kh);
        txtma.setText(kh.getMakh());
        txtten.setText(kh.getTenkh());
        txttuoi.setText(kh.getTuoi() + "");
        if (kh.getGioitinh().equals("Nam")) {
            txtnu.setSelected(true);
        } else {
            txtnam.setSelected(true);
        }
        txtdiachi.setSelectedItem(kh.getDiachi());
        txttrangthai.setSelected(kh.isTrangthai());
        txtso.setText("Record " + (index + 1) + " of " + list.size());
        table.setRowSelectionInterval(vip, vip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        txtnam = new javax.swing.JRadioButton();
        txtnu = new javax.swing.JRadioButton();
        txtdiachi = new javax.swing.JComboBox<>();
        txttrangthai = new javax.swing.JCheckBox();
        butthem = new javax.swing.JButton();
        butsua = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butthoat = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txttim = new javax.swing.JTextField();
        buttim = new javax.swing.JButton();
        butdau = new javax.swing.JButton();
        buttien = new javax.swing.JButton();
        butlui = new javax.swing.JButton();
        butcuoi = new javax.swing.JButton();
        txtso = new javax.swing.JLabel();
        mofile = new javax.swing.JButton();
        txtdongho = new javax.swing.JLabel();
        butr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý khách hàng");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Tuổi KH", "Giới tính", "Địa chỉ", "Trạng thái"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("Tên khách hàng");

        jLabel4.setText("Tuổi khách hàng");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Địa chỉ");

        jLabel7.setText("Trạng thái");

        buttonGroup1.add(txtnam);
        txtnam.setText("Nam");

        buttonGroup1.add(txtnu);
        txtnu.setText("Nữ");

        txtdiachi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Bắc Giang" }));

        txttrangthai.setText("Giàu?");

        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butsua.setText("Sửa");
        butsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsuaActionPerformed(evt);
            }
        });

        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        butthoat.setText("Thoát và lưu");
        butthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthoatActionPerformed(evt);
            }
        });

        jButton5.setText("Clear form");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttim.setText("Tìm ");
        buttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttimActionPerformed(evt);
            }
        });

        butdau.setText("<|");
        butdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdauActionPerformed(evt);
            }
        });

        buttien.setText("<<");
        buttien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttienActionPerformed(evt);
            }
        });

        butlui.setText(">>");
        butlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butluiActionPerformed(evt);
            }
        });

        butcuoi.setText(">|");
        butcuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcuoiActionPerformed(evt);
            }
        });

        txtso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtso.setForeground(new java.awt.Color(255, 0, 51));
        txtso.setText("jLabel8");

        mofile.setText("Mở file");
        mofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mofileActionPerformed(evt);
            }
        });

        txtdongho.setText("jLabel8");
        txtdongho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtdonghoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        butr.setText("Return");
        butr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtnu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtma)
                                        .addComponent(txtten)
                                        .addComponent(txttuoi)
                                        .addComponent(txtdiachi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(butr)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(butthem)
                                    .addGap(53, 53, 53)
                                    .addComponent(butsua)
                                    .addGap(70, 70, 70)
                                    .addComponent(butxoa))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(butthoat)
                                        .addGap(82, 82, 82)
                                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mofile)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(butdau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(butlui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(butcuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttim))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtdongho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtdongho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butdau)
                            .addComponent(buttien)
                            .addComponent(butlui)
                            .addComponent(butcuoi)
                            .addComponent(txtso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton5)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnam)
                                .addComponent(txtnu)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttrangthai))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(mofile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butr)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butthem)
                    .addComponent(butsua)
                    .addComponent(butxoa)
                    .addComponent(butthoat)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttim))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int vui;
    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
        // TODO add your handling code here:
        if (vui == -1) {
            Khachhang kh = new Khachhang();
            kh.setMakh(txtma.getText());
            kh.setTenkh(txtten.getText());
            kh.setTuoi(Integer.parseInt(txttuoi.getText()));
            if (txtnam.isSelected()) {
                kh.setGioitinh("Nam");
            } else {
                kh.setGioitinh("Nữ");
            }
            kh.setDiachi((String) txtdiachi.getSelectedItem());
            kh.setTrangthai(txttrangthai.isSelected());
            list.add(kh);
            addtable(list);
        } else {
            int sua = table.getSelectedRow();
            Khachhang kh = list.get(sua);
            kh.setMakh(txtma.getText());
            kh.setTenkh(txtten.getText());
            kh.setTuoi(Integer.parseInt(txttuoi.getText()));
            if (txtnam.isSelected()) {
                kh.setGioitinh("Nam");
            } else {
                kh.setGioitinh("Nữ");
            }
            kh.setDiachi((String) txtdiachi.getSelectedItem());
            kh.setTrangthai(txttrangthai.isSelected());
            addtable(list);
        }
    }//GEN-LAST:event_butthemActionPerformed

    private void butsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsuaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_butsuaActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        // TODO add your handling code here:
        int xoa = table.getSelectedRow();
        list.remove(xoa);
        addtable(list);
    }//GEN-LAST:event_butxoaActionPerformed

    private void butthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthoatActionPerformed
        // TODO add your handling code here:
        try {
            int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu không?");
            if (ma == 0) {
                FileOutputStream fos = new FileOutputStream("sang.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(list);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, "Bạn đã lưu thành công.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi");
        }
        System.exit(0);
    }//GEN-LAST:event_butthoatActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        txtma.setText(table.getValueAt(row, 0).toString());
        txtten.setText(table.getValueAt(row, 1).toString());
        txttuoi.setText(table.getValueAt(row, 2).toString());
        if (table.getValueAt(row, 3).toString().equals("Nam")) {
            txtnam.setSelected(true);
        } else {
            txtnu.setSelected(true);
        }
        txtdiachi.setSelectedItem(table.getValueAt(row, 4));
        txttrangthai.setSelected(table.getValueAt(row, 5).equals(true));
    }//GEN-LAST:event_tableMouseClicked

    private void buttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttimActionPerformed
        // TODO add your handling code here:
        for (Khachhang kh : list) {
            ArrayList<Khachhang> sc=new ArrayList<>();
            if (kh.getMakh().equalsIgnoreCase(txttim.getText())) {
                
                
                int ind = list.indexOf(kh);
                txtma.setText(kh.getMakh());
                txtten.setText(kh.getTenkh());
                txttuoi.setText(kh.getTuoi() + "");
                if (kh.getGioitinh().equals("Nam")) {
                    txtnu.setSelected(true);
                } else {
                    txtnam.setSelected(true);
                }
                txtdiachi.setSelectedItem(kh.getDiachi());
                txttrangthai.setSelected(kh.isTrangthai());
                sc.add(kh);
                addtable(sc);
                table.setRowSelectionInterval(ind, ind);
            }
        }
    }//GEN-LAST:event_buttimActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtten.setText("");
        txttuoi.setText("");
        txtnu.setSelected(false);
        txtnam.setSelected(false);
        txtdiachi.setSelectedItem("");
        txttrangthai.setSelected(false);
        vui = -1;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void butdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdauActionPerformed
        // TODO add your handling code here:
        index = 0;
        display();
    }//GEN-LAST:event_butdauActionPerformed

    private void butcuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcuoiActionPerformed
        // TODO add your handling code here:
        index = list.size() - 1;
        display();
    }//GEN-LAST:event_butcuoiActionPerformed

    private void buttienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttienActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
        }
        display();
    }//GEN-LAST:event_buttienActionPerformed

    private void butluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butluiActionPerformed
        // TODO add your handling code here:
        if (index < list.size() - 1) {
            index++;
        }
        display();
    }//GEN-LAST:event_butluiActionPerformed

    private void mofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mofileActionPerformed
        // TODO add your handling code here:
        try {
            int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn mở file không?");
            if (ma == 0) {
                FileInputStream fis = new FileInputStream("sang.dat");
                ObjectInputStream ois = new ObjectInputStream(fis);
                list = (ArrayList<Khachhang>) ois.readObject();
                if (list.size() > 0) {
                    addtable(list);
                }
            }
            JOptionPane.showMessageDialog(this, "bạn đã mở file thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi");
        }
    }//GEN-LAST:event_mofileActionPerformed

    private void txtdonghoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtdonghoAncestorAdded
        // TODO add your handling code here:
        dh dongh = new dh(txtdongho);
        dongh.start();
        txtdongho.setEnabled(true);

    }//GEN-LAST:event_txtdonghoAncestorAdded

    private void butrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrActionPerformed
        // TODO add your handling code here:
        addtable(list);
    }//GEN-LAST:event_butrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butcuoi;
    private javax.swing.JButton butdau;
    private javax.swing.JButton butlui;
    private javax.swing.JButton butr;
    private javax.swing.JButton butsua;
    private javax.swing.JButton butthem;
    private javax.swing.JButton butthoat;
    private javax.swing.JButton buttien;
    private javax.swing.JButton buttim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton butxoa;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mofile;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> txtdiachi;
    private javax.swing.JLabel txtdongho;
    private javax.swing.JTextField txtma;
    private javax.swing.JRadioButton txtnam;
    private javax.swing.JRadioButton txtnu;
    private javax.swing.JLabel txtso;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttim;
    private javax.swing.JCheckBox txttrangthai;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables
}
