/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formdayny;

import java.awt.List;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class quanlysinhvien extends javax.swing.JFrame {

    /**
     * Creates new form quanlysinhvien
     */
    public quanlysinhvien() {
        initComponents();

        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        list.add(new Student("sv1", "Nguyễn Ngọc Sáng", 18, "Nam", "Hà Nội", true));
        list.add(new Student("sv2", "Mai Hoàng Phương Anh", 18, "Nữ", "Hồ Chí Minh", false));
        list.add(new Student("sv3", "Nguyễn Văn Tùng", 19, "Nam", "Hà Nội", false));
        list.add(new Student("sv4", "Nguyễn Văn Nga", 18, "Nam", "Bắc Giang", true));
        addtable();

    }

    ArrayList<Student> list = new ArrayList<>();

    public void addtable() {
        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        bang.setRowCount(0);
        for (Student student : list) {
            bang.addRow(new Object[]{student.getMasv(), student.getTen(), student.getTuoi(), student.getGioitinh(), student.getDiachi(), student.isTinhtrang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        butsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        txtnam = new javax.swing.JRadioButton();
        txtnu = new javax.swing.JRadioButton();
        txtdiachi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txttinhtrang = new javax.swing.JCheckBox();
        butthem = new javax.swing.JButton();
        butsua = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butsapxep = new javax.swing.JButton();
        butthoat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        butdau = new javax.swing.JButton();
        buttien = new javax.swing.JButton();
        butlui = new javax.swing.JButton();
        butcuoi = new javax.swing.JButton();
        mo = new javax.swing.JButton();
        txtdongho = new javax.swing.JLabel();
        butsx = new javax.swing.JButton();
        sxten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Clear form");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tìm Kiếm");

        butsearch.setText("Search");
        butsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(butsearch)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butsearch))
                .addGap(23, 23, 23))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel2.setText("Mã sv");

        jLabel3.setText("Tên");

        jLabel4.setText("Tuổi");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Địa chỉ");

        buttonGroup1.add(txtnam);
        txtnam.setText("Nam");

        buttonGroup1.add(txtnu);
        txtnu.setText("Nữ");

        txtdiachi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Hồ Chí Minh", "Bắc Giang", " " }));

        jLabel7.setText("Tình trạng");

        txttinhtrang.setText("Tốt ?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtmasv, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addComponent(txtten)
                        .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnam)
                    .addComponent(txtnu))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttinhtrang))
                .addGap(17, 17, 17))
        );

        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butsua.setText("Sửa");
        butsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsuaActionPerformed(evt);
            }
        });

        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        butsapxep.setText("Sắp xếp");

        butthoat.setText("Thoát");
        butthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthoatActionPerformed(evt);
            }
        });

        jLabel8.setText("List data");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sv", "Tên", "Tuổi", "Giới tính", "Địa chỉ", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        butdau.setText("|<");
        butdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdauActionPerformed(evt);
            }
        });

        buttien.setText("<<");
        buttien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttienActionPerformed(evt);
            }
        });

        butlui.setText(">>");
        butlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butluiActionPerformed(evt);
            }
        });

        butcuoi.setText(">|");
        butcuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcuoiActionPerformed(evt);
            }
        });

        mo.setText("Mở file");
        mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moActionPerformed(evt);
            }
        });

        txtdongho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdongho.setForeground(new java.awt.Color(255, 0, 0));
        txtdongho.setText("jLabel9");
        txtdongho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtdonghoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        butsx.setText("Sắp xếp tuổi");
        butsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsxActionPerformed(evt);
            }
        });

        sxten.setText("Sắp xếp tên");
        sxten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sxtenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butthem)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(butdau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttien, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(butsua)
                                .addGap(18, 18, 18)
                                .addComponent(butxoa)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(butlui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butcuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(butsx)
                                .addGap(18, 18, 18)
                                .addComponent(sxten))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mo)
                                .addGap(18, 18, 18)
                                .addComponent(butsapxep)
                                .addGap(18, 18, 18)
                                .addComponent(butthoat))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdongho, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtdongho))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butthem)
                    .addComponent(butsua)
                    .addComponent(butxoa)
                    .addComponent(butsapxep)
                    .addComponent(butthoat)
                    .addComponent(mo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(butdau)
                    .addComponent(buttien)
                    .addComponent(butlui)
                    .addComponent(butcuoi)
                    .addComponent(butsx)
                    .addComponent(sxten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
        // TODO add your handling code here:
        if(txtten.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ten khong de trong");
        }
        if(!txttuoi.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "tuoi phai là số và không đc nhỏ hơn 0");
        }
        else{
        
        Student sv = new Student();
        sv.setMasv(txtmasv.getText());
        sv.setTen(txtten.getText());
        sv.setTuoi(Integer.parseInt(txttuoi.getText()));
        if (txtnam.isSelected()) {
            sv.setGioitinh("Nam");
        } else {
            sv.setGioitinh("Nữ");
        }
        sv.setDiachi((String) txtdiachi.getSelectedItem());
        sv.setTinhtrang(txttinhtrang.isSelected());
        list.add(sv);
        addtable();}
    }//GEN-LAST:event_butthemActionPerformed
    int index = 0;

    public void showd() {
        Student nv = list.get(index);
        int vitri = list.indexOf(nv);
        txtmasv.setText(nv.getMasv());
        txtten.setText(nv.getTen());
        txttuoi.setText(nv.getTuoi() + "");
        if (nv.getGioitinh().toString().equals("Nam")) {
            txtnam.setSelected(true);
        } else {
            txtnu.setSelected(true);
        }
        txtdiachi.setSelectedItem(nv.getDiachi());
        txttinhtrang.setSelected(nv.isTinhtrang());
        table.setRowSelectionInterval(index, index);
    }

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
//         TODO add your handling code here:
        int row = table.getSelectedRow();
        txtmasv.setText(table.getValueAt(row, 0).toString());
        txtten.setText(table.getValueAt(row, 1).toString());
        txttuoi.setText(table.getValueAt(row, 2).toString());
        if (table.getValueAt(row, 3).toString().equals("Nam")) {
            txtnam.setSelected(true);
        } else {
            txtnu.setSelected(true);
        }
        txtdiachi.setSelectedItem(table.getValueAt(row, 4).toString());
        txttinhtrang.setSelected(table.getValueAt(row, 5).equals(true));
    }//GEN-LAST:event_tableMouseClicked

    private void butsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsuaActionPerformed
        // TODO add your handling code here:
        int sua = table.getSelectedRow();
        Student sv = list.get(sua);
        sv.setMasv(txtmasv.getText());
        sv.setTen(txtten.getText());
        sv.setTuoi(Integer.parseInt(txttuoi.getText()));
        if (txtnam.isSelected()) {
            sv.setGioitinh("Nam");
        } else {
            sv.setGioitinh("Nữ");
        }
        sv.setDiachi((String) txtdiachi.getSelectedItem());
        sv.setTinhtrang(txttinhtrang.isSelected());
        addtable();
    }//GEN-LAST:event_butsuaActionPerformed

    private void butsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsearchActionPerformed
        // TODO add your handling code here:
        for (Student student : list) {
            if (student.getMasv().equalsIgnoreCase(txttimkiem.getText())) {
//                int ind=list.indexOf(student);
//                txtmasv.setText(student.getMasv());
//                txtten.setText(student.getTen());
//                txttuoi.setText(student.getTuoi()+"");
//                if(student.getGioitinh().toString().equals("Nam")){
//                    txtnam.setSelected(true);
//                }else{ 
//                    txtnu.setSelected(true);
//                }
//                txtdiachi.setSelectedItem(student.getDiachi());
//                txttinhtrang.setSelected(student.isTinhtrang());
//                table.setRowSelectionInterval(ind, ind);
                index = list.indexOf(student);
                showd();
            }
        }
    }//GEN-LAST:event_butsearchActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        // TODO add your handling code here:
        int xoa = table.getSelectedRow();
        list.remove(xoa);
        addtable();
    }//GEN-LAST:event_butxoaActionPerformed

    private void butthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthoatActionPerformed
        // TODO add your handling code here:
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát và lưu không");

            if (hoi == 0) {
                FileOutputStream fos = new FileOutputStream("sang.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(list);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, "Ghi thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        System.exit(0);

    }//GEN-LAST:event_butthoatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtmasv.setText("");
        txtten.setText("");
        txttuoi.setText("");
        txtnam.setText("");
        txtnu.setText("");
        txtdiachi.setSelectedItem("");
        txttinhtrang.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdauActionPerformed
        // TODO add your handling code here:
        index = 0;
        showd();
    }//GEN-LAST:event_butdauActionPerformed

    private void butcuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcuoiActionPerformed
        // TODO add your handling code here:
        index = list.size() - 1;
        showd();
    }//GEN-LAST:event_butcuoiActionPerformed

    private void buttienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttienActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
            showd();
        }
    }//GEN-LAST:event_buttienActionPerformed

    private void butluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butluiActionPerformed
        // TODO add your handling code here:
        if (index < list.size() - 1) {
            index++;
            showd();
        }
    }//GEN-LAST:event_butluiActionPerformed

    private void moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("sang.dat");
            ObjectInputStream oos = new ObjectInputStream(fis);
            list = (ArrayList<Student>) oos.readObject();
            if (list.size() > 0) {
                addtable();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_moActionPerformed

    private void txtdonghoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtdonghoAncestorAdded
        // TODO add your handling code here:
        dongho dd = new dongho(txtdongho);
        dd.start();
        txtdongho.setEnabled(true);
    }//GEN-LAST:event_txtdonghoAncestorAdded

    private void butsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsxActionPerformed
        // TODO add your handling code here:
        list.sort(new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.getTuoi() - o2.getTuoi();
            }
        }
        );
        addtable();
    }//GEN-LAST:event_butsxActionPerformed

    private void sxtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sxtenActionPerformed
        // TODO add your handling code here:
        list.sort( new Comparator<Student>(){
            @Override
            public int compare(Student o1, Student o2) {
                return o1.getTen().compareTo(o2.getTen());
            }
        }
        );
        addtable();
    }//GEN-LAST:event_sxtenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlysinhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butcuoi;
    private javax.swing.JButton butdau;
    private javax.swing.JButton butlui;
    private javax.swing.JButton butsapxep;
    private javax.swing.JButton butsearch;
    private javax.swing.JButton butsua;
    private javax.swing.JButton butsx;
    private javax.swing.JButton butthem;
    private javax.swing.JButton butthoat;
    private javax.swing.JButton buttien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton butxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mo;
    private javax.swing.JButton sxten;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> txtdiachi;
    private javax.swing.JLabel txtdongho;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JRadioButton txtnam;
    private javax.swing.JRadioButton txtnu;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JCheckBox txttinhtrang;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables

    private FileInputStream FileInputStream(String sangtxt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private ObjectInputStream ObjectInputStream(FileInputStream fis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
