/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lad_3;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Bai1 extends javax.swing.JFrame {

    ArrayList<Student> list = new ArrayList<>();

    public void themstudent() {
        Student sv = new Student();
        sv.hovaten = txthovaten.getText();
        sv.diem = Double.parseDouble(txtdiem.getText());
        sv.chuyennganh = (String) nganh.getSelectedItem();
        list.add(sv);
        txthocluc.setText(sv.getGrade());
        txtthuong.setSelected(sv.isBunus());
    }

    public void xoastudent() {
        int xoa = table.getSelectedRow();
        list.remove(xoa);
    }

    public void capnhatstudent() {
        int capnhat = table.getSelectedRow();
        Student sv = list.get(capnhat);
        sv.hovaten = txthovaten.getText();
        sv.diem = Double.parseDouble(txtdiem.getText());
        sv.chuyennganh = (String) nganh.getSelectedItem();
        txthocluc.setText(sv.getGrade());
        txtthuong.setSelected(sv.isBunus());
    }

    public void themvaobang() {
        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        bang.setRowCount(0);
        for (Student student : list) {
            bang.addRow(new Object[]{student.getHovaten(), student.getDiem(), student.getChuyennganh(), student.getGrade(), student.isBunus()});
        }
    }

    public void xoatrang() {
        txthovaten.setText("");
        txtdiem.setText("");
        txthocluc.setText("");
        txtthuong.setSelected(false);
    }

    public void sapxepten() {
        list.sort(new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.getHovaten().compareTo(o2.getHovaten());
            }
        }
        );
    }

    public void saptheodiem() {
        list.sort(new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return (int) (o1.getDiem() - o2.getDiem());
            }

        }
        );
    }

    public void kiemtra() {
        String hovaten = txthovaten.getText();
        String diem = txtdiem.getText();
        StringBuilder sang = new StringBuilder();
        if (hovaten.equals("")) {
            sang.append("Bạn chưa nhập tên\n");
        }
        if (diem.equals("")) {
            sang.append("Bạn chưa nhập điểm");
        }
        if (sang.length() > 0) {
            JOptionPane.showMessageDialog(this, sang.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    int vitri;

    public void display(int vitri) {
        txthovaten.setText(list.get(vitri).getHovaten());
        txtdiem.setText(list.get(vitri).getDiem() + "");
        txthocluc.setText(list.get(vitri).getGrade());

    }

    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txthovaten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nganh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txthocluc = new javax.swing.JTextField();
        txtthuong = new javax.swing.JCheckBox();
        butthem = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butcapnhat = new javax.swing.JButton();
        butnhapmoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        butxepten = new javax.swing.JButton();
        butxepdiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý sinh viên");

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Điểm:");

        jLabel4.setText("Ngành:");

        nganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết kế webidte", "Ứng dụn phần mềm", "Quản trị kinh doanh", " " }));

        jLabel5.setText("Học lực:");

        txtthuong.setText("Có phần thưởng");

        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        butcapnhat.setText("Cập nhật");
        butcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcapnhatActionPerformed(evt);
            }
        });

        butnhapmoi.setText("Nhập mới");
        butnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnhapmoiActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ và tên", "Điểm", "Ngành", "Học Lực", "Thưởng"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        butxepten.setText("Sắp xếp theo tên");
        butxepten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxeptenActionPerformed(evt);
            }
        });

        butxepdiem.setText("Sắp xếp theo điểm");
        butxepdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxepdiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtthuong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(butcapnhat)
                                                .addGap(50, 50, 50)
                                                .addComponent(butnhapmoi))
                                            .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(butthem)
                                .addGap(53, 53, 53)
                                .addComponent(butxoa))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdiem, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                                    .addComponent(txthovaten)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(butxepten, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(butxepdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtthuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butthem)
                    .addComponent(butxoa)
                    .addComponent(butcapnhat)
                    .addComponent(butnhapmoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butxepten)
                    .addComponent(butxepdiem))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
        // TODO add your handling code here:
        this.kiemtra();
        this.themstudent();
        vitri = list.size() - 1;
        display(vitri);
        this.themvaobang();

    }//GEN-LAST:event_butthemActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        // TODO add your handling code here:
        this.xoastudent();
        this.themvaobang();
    }//GEN-LAST:event_butxoaActionPerformed

    private void butcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcapnhatActionPerformed
        // TODO add your handling code here:
        this.capnhatstudent();
        this.themvaobang();

    }//GEN-LAST:event_butcapnhatActionPerformed

    private void butnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnhapmoiActionPerformed
        // TODO add your handling code here:
        this.xoastudent();
        this.themvaobang();
    }//GEN-LAST:event_butnhapmoiActionPerformed

    private void butxeptenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxeptenActionPerformed
        // TODO add your handling code here:
        this.sapxepten();
        this.themvaobang();
    }//GEN-LAST:event_butxeptenActionPerformed

    private void butxepdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxepdiemActionPerformed
        // TODO add your handling code here:
        this.saptheodiem();
        this.themvaobang();
    }//GEN-LAST:event_butxepdiemActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row > 0) {
            vitri = row;
            display(vitri);
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butcapnhat;
    private javax.swing.JButton butnhapmoi;
    private javax.swing.JButton butthem;
    private javax.swing.JButton butxepdiem;
    private javax.swing.JButton butxepten;
    private javax.swing.JButton butxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> nganh;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txthocluc;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JCheckBox txtthuong;
    // End of variables declaration//GEN-END:variables
}
