/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.learnlad2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class bang extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form bang
     */
    public bang() {
        initComponents();
        tableModel = (DefaultTableModel) tblListStudent.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tpnUpdateStudent = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListStudent = new javax.swing.JTable();
        pnUpdate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        txtYOB = new javax.swing.JTextField();
        cboClassName = new javax.swing.JComboBox<>();
        txtFinalGrade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        chkStatus = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manage Student");

        tblListStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PHP17238", "Vu Thi Thuy", "Nu", "2002", "CP17310",  new Double(8.5), "Gioi",  new Boolean(true)},
                {"PHP18271", "Tran Huu Thien", "Nam", "2001", "CP17311",  new Double(7.0), "Kha",  new Boolean(true)},
                {"PH182474", "Nguyen Anh Tuan", "Nam", "2000", "CP17481",  new Double(6.0), "Trung Binh",  new Boolean(true)},
                {"PH12321", "Nguyen Thi Tram", "Nu", "1999", "EC12281",  new Double(5.5), "Trung Binh",  new Boolean(true)},
                {"PH11232", "Pham Thi Tram", "Nu", "2003", "IT18237",  new Double(4.75), "Yeu", null}
            },
            new String [] {
                "No", "Name", "Gender", "YOB", "Class Name", "Final Grade", "Notes", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListStudent);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpnUpdateStudent.addTab("List", jPanel1);

        jLabel2.setText("Student Number");

        jLabel3.setText("Student Name");

        jLabel4.setText("Gender");

        jLabel5.setText("Year Of Birth");

        jLabel6.setText("Class");

        jLabel7.setText("Final grade");

        jLabel8.setText("Notes");

        jLabel9.setText("Status");

        rdoMale.setSelected(true);
        rdoMale.setText("Male");

        rdoFemale.setText("Female");

        cboClassName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CP17310", "CP17777", "EC17333", "IT18211" }));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        chkStatus.setText("Graduated ?");

        javax.swing.GroupLayout pnUpdateLayout = new javax.swing.GroupLayout(pnUpdate);
        pnUpdate.setLayout(pnUpdateLayout);
        pnUpdateLayout.setHorizontalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStudentNo)
                            .addComponent(txtStudentName)
                            .addGroup(pnUpdateLayout.createSequentialGroup()
                                .addComponent(rdoMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(rdoFemale))
                            .addComponent(txtYOB)
                            .addComponent(cboClassName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFinalGrade))
                        .addContainerGap(376, Short.MAX_VALUE))
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addGroup(pnUpdateLayout.createSequentialGroup()
                                .addComponent(chkStatus)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnUpdateLayout.setVerticalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoMale)
                    .addComponent(rdoFemale))
                .addGap(24, 24, 24)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtYOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFinalGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkStatus)))
                .addContainerGap())
        );

        tpnUpdateStudent.addTab("Update", pnUpdate);

        btnReset.setText("Reset");

        btnAddNew.setText("Add new");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnAddNew)
                .addGap(108, 108, 108)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(72, 72, 72)
                .addComponent(btnReset)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tpnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddNew)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnReset))
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListStudentMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblListStudent.getSelectedRow();
        txtStudentNo.setText((tableModel.getValueAt(selectedRowIndex, 0)).toString());
        txtStudentName.setText((tableModel.getValueAt(selectedRowIndex, 1)).toString());

        if ((tableModel.getValueAt(selectedRowIndex, 2)).toString().equals("Nam")) {
            rdoMale.setSelected(true);
        } else {
            rdoFemale.setSelected(true);
        }

        txtYOB.setText((tableModel.getValueAt(selectedRowIndex, 3)).toString());
        cboClassName.setSelectedItem((tableModel.getValueAt(selectedRowIndex, 4)).toString());
        txtFinalGrade.setText((tableModel.getValueAt(selectedRowIndex, 5)).toString());
        txtNotes.setText((tableModel.getValueAt(selectedRowIndex, 6)).toString());
        chkStatus.setSelected((tableModel.getValueAt(selectedRowIndex, 7)).toString().equals("true"));

        tpnUpdateStudent.setSelectedIndex(1);
    }//GEN-LAST:event_tblListStudentMouseClicked

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        Student newStudent = new Student();
        // Lay gia tri trong o nhap student number
        newStudent.setStudentNo(txtStudentNo.getText());
        newStudent.setStudentName(txtStudentName.getText());

        // Kiem tra gioi tinh Nam hay Nu
        if (rdoMale.isSelected()) {
            newStudent.setGender("Nam");
        } else {
            newStudent.setGender("Nu");
        }

        newStudent.setYob(Integer.parseInt(txtYOB.getText()));
        newStudent.setClassName(cboClassName.getSelectedItem().toString());
        newStudent.setNotes(txtNotes.getText());
        newStudent.setStatus(chkStatus.isSelected());

        // INSERT NEW STUDENT
        tableModel.addRow(new Object[] {
            newStudent.getStudentNo(), newStudent.getStudentName(),
            newStudent.getGender(), newStudent.getYob(), newStudent.getClassName(),
            newStudent.getFinalGrade(), newStudent.getNotes(), newStudent.isStatus()
        });

        JOptionPane.showMessageDialog(this, "Add success");

    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         Student newStudent = new Student();
        // Lay gia tri trong o nhap student number
        newStudent.setStudentNo(txtStudentNo.getText());
        newStudent.setStudentName(txtStudentName.getText());

        // Kiem tra gioi tinh Nam hay Nu
        if (rdoMale.isSelected()) {
            newStudent.setGender("Nam");
        } else {
            newStudent.setGender("Nu");
        }

        newStudent.setYob(Integer.parseInt(txtYOB.getText()));
        newStudent.setClassName(cboClassName.getSelectedItem().toString());
        newStudent.setNotes(txtNotes.getText());
        newStudent.setStatus(chkStatus.isSelected());
        
        int row=tblListStudent.getSelectedRow();
        tableModel.setValueAt(newStudent.getStudentNo(), row, 0);
        tableModel.setValueAt(newStudent.getStudentName(), row, 1);
        tableModel.setValueAt(newStudent.getGender(), row, 2);
        tableModel.setValueAt(newStudent.getYob(), row, 3);
        tableModel.setValueAt(newStudent.getClassName(), row, 4);
        tableModel.setValueAt(newStudent.getFinalGrade(), row, 5);
        tableModel.setValueAt(newStudent.getNotes(), row, 6);
        tableModel.setValueAt(newStudent.isStatus(), row, 7);
        
        tpnUpdateStudent.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tblListStudent.getSelectedRow()>=0){
            int iscom=JOptionPane.showConfirmDialog(this, "bạn muốn xóa không");
            if(iscom==0){
                tableModel.removeRow(tblListStudent.getSelectedRow());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboClassName;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnUpdate;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblListStudent;
    private javax.swing.JTabbedPane tpnUpdateStudent;
    private javax.swing.JTextField txtFinalGrade;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentNo;
    private javax.swing.JTextField txtYOB;
    // End of variables declaration//GEN-END:variables
}
