/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baikiemtra78;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChieuPhim extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form ChieuPhim
     */
    ArrayList<ChieuP> list = new ArrayList<>();

    public ChieuPhim() {
        initComponents();
        list.add(new ChieuP("a", "Hanh dong", 3, "Mavel"));
        list.add(new ChieuP("a", "Hanh dong", 3, "Mavel"));
        list.add(new ChieuP("f", "Hanh dong", 6, "Mavel"));
        list.add(new ChieuP("a", "Tinh cam", 3, "Mavel"));
        addtable();
        index = 0;
        display();

        Thread tr = new Thread(this);
        tr.start();
    }

    public void addtable() {
        DefaultTableModel bang = (DefaultTableModel) table.getModel();
        bang.setRowCount(0);
        for (ChieuP cp : list) {
            bang.addRow(new Object[]{cp.getTen(), cp.getTheloai(), cp.getGiave(), cp.getHangphim()});
        }
    }
    int index;

    public void display() {
        ChieuP cp = list.get(index);
        txtten.setText(cp.getTen());
        if (cp.getTheloai().equals("Hanh dong")) {
            rahd.setSelected(true);
        } else if (cp.getTheloai().equals("Tinh cam")) {
            ratc.setSelected(true);
        } else if (cp.getTheloai().equals("Kinh di")) {
            rakd.setSelected(true);
        } else if (cp.getTheloai().equals("Hai huoc")) {
            rahh.setSelected(true);
        }
        txtgiave.setText(cp.getGiave() + "");
        cbtheloai.setSelectedItem(cp.getHangphim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rahd = new javax.swing.JRadioButton();
        ratc = new javax.swing.JRadioButton();
        rakd = new javax.swing.JRadioButton();
        rahh = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtgiave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbtheloai = new javax.swing.JComboBox<>();
        butthem = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butmo = new javax.swing.JButton();
        butghi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        dongho = new javax.swing.JLabel();
        dhdem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên");

        text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 51, 51));
        text.setText("QUẢN LÝ PHIM CHIẾU RẠP");

        jLabel3.setText("Thể loại");

        buttonGroup1.add(rahd);
        rahd.setText("Hanh dong");

        buttonGroup1.add(ratc);
        ratc.setText("Tinh cam");

        buttonGroup1.add(rakd);
        rakd.setText("Kinh di");

        buttonGroup1.add(rahh);
        rahh.setText("Hai huoc");

        jLabel4.setText("Giá vé");

        jLabel5.setText("Hàng phim");

        cbtheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mavel", "Daier", "Chill" }));

        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        butmo.setText("Mở file");
        butmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butmoActionPerformed(evt);
            }
        });

        butghi.setText("Ghi file");
        butghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butghiActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ten", "The loai", "Gia ve", "Hang phim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        dongho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dongho.setForeground(new java.awt.Color(255, 0, 51));
        dongho.setText("jLabel6");
        dongho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                donghoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        dhdem.setBackground(new java.awt.Color(255, 255, 0));
        dhdem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dhdem.setForeground(new java.awt.Color(51, 255, 0));
        dhdem.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(text)))
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(butthem)
                        .addGap(33, 33, 33)
                        .addComponent(butxoa)
                        .addGap(36, 36, 36)
                        .addComponent(butmo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rahd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ratc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtgiave, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rakd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rahh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbtheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butghi)
                            .addComponent(dhdem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dongho, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(text)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dhdem))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rahd)
                    .addComponent(ratc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rakd)
                    .addComponent(rahh)
                    .addComponent(dongho))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgiave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbtheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butthem)
                    .addComponent(butxoa)
                    .addComponent(butmo)
                    .addComponent(butghi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
        // TODO add your handling code here:
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên");
        }
        if (txtgiave.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập giá vé");
        } else if (!txtgiave.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Giá vé phải là số và lớn hơn 0");
        }

        ChieuP cp = new ChieuP();
        cp.setTen(txtten.getText());
        if (rahd.isSelected()) {
            cp.setTheloai("Hanh dong");
        } else if (ratc.isSelected()) {
            cp.setTheloai("Tinh cam");
        } else if (rakd.isSelected()) {
            cp.setTheloai("Kinh di");
        } else if (rahh.isSelected()) {
            cp.setTheloai("Hai huoc");
        }
        cp.setGiave(Integer.parseInt(txtgiave.getText()));
        cp.setHangphim((String) cbtheloai.getSelectedItem());
        list.add(cp);
        addtable();


    }//GEN-LAST:event_butthemActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        list.remove(row);
        addtable();
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_butxoaActionPerformed

    private void butghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butghiActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("a.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(list);
            oos.close();
            JOptionPane.showMessageDialog(this, "Ghi thành công");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_butghiActionPerformed

    private void butmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butmoActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("a.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            list = (ArrayList<ChieuP>) ois.readObject();
            if (list.size() >= 0) {
                addtable();
                JOptionPane.showMessageDialog(this, "Đọc file thành công");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_butmoActionPerformed

    private void donghoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_donghoAncestorAdded
        // TODO add your handling code here:

        dongho dh = new dongho(dongho);
        dh.start();
        dongho.setEnabled(true);
    }//GEN-LAST:event_donghoAncestorAdded

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int ro = table.getSelectedRow();
        if (ro >= 0) {
            index = ro;
            display();
        }


    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChieuPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChieuPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChieuPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChieuPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChieuPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butghi;
    private javax.swing.JButton butmo;
    private javax.swing.JButton butthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton butxoa;
    private javax.swing.JComboBox<String> cbtheloai;
    private javax.swing.JLabel dhdem;
    private javax.swing.JLabel dongho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rahd;
    private javax.swing.JRadioButton rahh;
    private javax.swing.JRadioButton rakd;
    private javax.swing.JRadioButton ratc;
    private javax.swing.JTable table;
    private javax.swing.JLabel text;
    private javax.swing.JTextField txtgiave;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        String chuoi=text.getText();
        while (true) {            
            String ch=chuoi.substring(0,1);
            chuoi=chuoi.substring(1).concat(ch);
            text.setText(chuoi);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(ChieuPhim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    

}
